CREATE DATABASE IF NOT EXISTS Liftdb DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
USE Liftdb;

CREATE TABLE IF NOT EXISTS ActionLogs (
  Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DATE DATE NOT NULL,
  TIME TIME NOT NULL,
  ACTIONS VARCHAR(500) NOT NULL,
  PRIMARY KEY (Id),
  KEY idx_date_time (DATE,TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ActionLogs (DATE, TIME, ACTIONS)
VALUES (CURRENT_DATE(), CURRENT_TIME(), 'Test log from SQL client');

SELECT Id, DATE, TIME, ACTIONS FROM ActionLogs ORDER BY Id DESC LIMIT 10;
